import {Dimensions, Platform, StyleSheet} from 'react-native';

const SCREEN_WIDTH = Dimensions.get('window').width;
const SCREEN_HEIGHT = Dimensions.get('window').height;
const squareSize = (SCREEN_WIDTH * 4) / 5;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'black',
  },
  image: {
    backgroundColor: 'black',
  },
  viewTop: {
    position: 'absolute',
    justifyContent: 'space-between',
    flexDirection: 'row',
    flex: 1,
    width: SCREEN_WIDTH,
    top: Platform.OS == 'android' ? 20 : 60,
    paddingLeft: 20,
    paddingRight: 20,
    gap: 20,
    marginTop: 12,
  },
  viewBottom: {
    position: 'absolute',
    bottom: 20,
    justifyContent: 'space-between',
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 30,
  },
  zoomBar: {
    position: 'absolute',
    bottom: 160,
    width: SCREEN_WIDTH,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 20,
  },
  zoomText: {
    color: 'white',
    fontSize: 14,
    height: 30,
    width: 30,
    textAlign: 'center',
    lineHeight: 30,
    borderRadius: 15,
    fontWeight: 'bold',
    backgroundColor: '#00000070',
  },
  permissionContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'black',
  },
  permissionText: {
    color: 'white',
    fontSize: 16,
    marginBottom: 20,
  },
  permissionButton: {
    backgroundColor: '#007AFF',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
  },
  permissionButtonText: {
    color: 'white',
    fontSize: 16,
  },
  recordingTimeContainer: {
    position: 'absolute',
    top: 40,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  recordingIndicator: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#FF0000',
    marginRight: 8,
  },
  recordingTimeText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    textShadowColor: 'rgba(0, 0, 0, 0.75)',
    textShadowOffset: {width: 1, height: 1},
    textShadowRadius: 2,
  },
  previewButton: {
    width: 70,
    height: 100,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    borderWidth: 2,
    borderColor: 'white',
  },
  previewThumbnail: {
    width: '100%',
    height: '100%',
  },
  previewOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  previewModalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeButton: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 50 : 20,
    right: 20,
    zIndex: 1000,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  previewVideo: {
    width: SCREEN_WIDTH,
    height: SCREEN_HEIGHT * 0.8,
  },
  headFootStyle: {
    position: 'absolute',
    left: 0,
    width: SCREEN_WIDTH,
    height: (SCREEN_HEIGHT - squareSize) / 2,
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
  },
  sideStyle: {
    position: 'absolute',
    bottom: (SCREEN_HEIGHT - squareSize) / 2,
    width: (SCREEN_WIDTH - squareSize) / 2,
    height: squareSize,
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
  },
});
